### ISSUE TITLE
Out of memory during the input sanitization in s390.c plugin

### ISSUE THREAD

**Issue by poncovka** [rhinstaller/libblockdev#149]
Functions `bd_s390_sanitize_dev_input` and  `bd_s390_zfcp_sanitize_lun_input` can cause an out of memory error for invalid input.

For example in the command `prepend = g_strnfill((4 - strlen(tmptok)), '0');`, the length of the string `tmpok` is not checked, therefore `4 - strlen(tmptok)` could be a negative number. However, `g_strnfill` expects an unsigned long integer, so the number will be converted to a very large number and `g_strnfill` will try to create a string of this length.

Problematic inputs:
`bd_s390_sanitize_dev_input("123456")`
`bd_s390_zfcp_sanitize_wwpn_input("12345678901234567890")`

**Comment by vpodzime** [comment]
Thanks for the report!
