### ISSUE TITLE
improve error granularity

### ISSUE THREAD

**Issue by dwlehman** [rhinstaller/libblockdev#2]
As of now, all errors raised by libblockdev are GLib.GError which, while sufficient, is not ideal for users like blivet. Ideally, libblockdev could increase the granularity of the errors it raises while also making them less generic.

@vpodzime mentioned the possibility of an error proxy in the BlockDev.py gi overrides, which sounds like a nice solution.

**Comment by vpodzime** [comment]
Resolved by PR #4
