### ISSUE TITLE
Make distcheck fails

### ISSUE THREAD

**Issue by tasleson** [rhinstaller/libblockdev#202]
I wanted to simply run the local unit tests and ran `make ci` which ends with:

``` make
...
make[1]: Entering directory '/home/tasleson/projects/libblockdev'
if test -d "libblockdev-2.7"; then find "libblockdev-2.7" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "libblockdev-2.7" || { sleep 5 && rm -rf "libblockdev-2.7"; }; else :; fi
test -d "libblockdev-2.7" || mkdir "libblockdev-2.7"
cp: failed to preserve ownership for libblockdev-2.7/tests/lvm_dbus_config/10-lvm-dbus.cfg: No such file or directory
cp: failed to preserve ownership for libblockdev-2.7/tests/lvm_dbus_config/00-default.cfg: No such file or directory
cp: failed to preserve ownership for libblockdev-2.7/tests/default_config/00-default.cfg: No such file or directory
make[1]: *** [Makefile:575: distdir] Error 1
make[1]: Leaving directory '/home/tasleson/projects/libblockdev'
make: *** [Makefile:672: dist] Error 2
```

I then used `make test` which it likely what I wanted to begin with.

**Comment by vpodzime** [comment]
How did you run ``./configure``? I've just tried ``make distcheck`` on two systems and it worked just fine. We are also running ``distcheck`` as part of ``make ci`` in our CI where it passed on all distro-version-arch combinations.

**Comment by vpodzime** [comment]
Maybe some leftovers? Please try it again after running ``sudo git clean -xdf``

**Comment by tasleson** [comment]
F26, clean and up to date, running `./autogen.sh && ./configure && make && make distcheck` still fails with error message posted above.  Which branch should I be in?  I'm just using master.

**Comment by vpodzime** [comment]
I just did a new, clean installation of Fedora 26, clean clone of the *libblockdev* git repository, installed the build dependencies and run the above commands without any issues. Could you please try the same?

**Comment by tasleson** [comment]
This problem is caused because I'm using sshfs to share my files from home home directory to a VM I'm developing on.  Sorry about the noise!  I tried NFS long ago, but ran into problems with file edits on server side taking too long to be propagated to client.  Need to rethink my work flow I guess.  Sorry for the noise!

**Comment by vpodzime** [comment]
> This problem is caused because I'm using sshfs to share my files from home home directory to a VM I'm developing on. Sorry about the noise! I tried NFS long ago, but ran into problems with file edits on server side taking too long to be propagated to client. Need to rethink my work flow I guess. Sorry for the noise!

Interesting. I wouldn't have expected that to make any difference. But maybe you need GlusterFS? ;)
