### ISSUE TITLE
libblockdev-2.8 fails to compile

### ISSUE THREAD

**Issue by tgurr** [rhinstaller/libblockdev#205]
gcc (GCC) 6.3.0
systemd 233

`./configure --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --prefix=/usr/x86_64-pc-linux-gnu --bindir=/usr/x86_64-pc-linux-gnu/bin --sbindir=/usr/x86_64-pc-linux-gnu/bin --libdir=/usr/x86_64-pc-linux-gnu/lib --datadir=/usr/share --datarootdir=/usr/share --docdir=/usr/share/doc/libblockdev-2.8 --infodir=/usr/share/info --mandir=/usr/share/man --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --enable-fast-install --enable-introspection --with-python3 --without-gtk-doc --without-bcache --without-btrfs --without-crypto --without-dm --without-loop --without-lvm --without-lvm_dbus --without-mdraid --without-mpath --without-swap --without-kbd --without-part --without-fs --enable-tests`

```
[...]
/bin/sh ../../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-cc -I/usr/x86_64-pc-linux-gnu/include/glib-2.0 -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include  -Wall -Wextra -Werror -pipe -O2 -march=native -version-info 3:0:1 -Wl,--no-undefined  -o libbd_utils.la -rpath /usr/x86_64-pc-linux-gnu/lib libbd_utils_la-exec.lo libbd_utils_la-extra_arg.lo libbd_utils_la-dev_utils.lo -lglib-2.0 -lm -lgio-2.0 -lgobject-2.0 -lglib-2.0  
libtool: link: x86_64-pc-linux-gnu-cc -shared  -fPIC -DPIC  .libs/libbd_utils_la-exec.o .libs/libbd_utils_la-extra_arg.o .libs/libbd_utils_la-dev_utils.o   -Wl,-rpath -Wl,/usr/x86_64-pc-linux-gnu/lib -Wl,-rpath -Wl,/usr/x86_64-pc-linux-gnu/lib -lm /usr/x86_64-pc-linux-gnu/lib/libgio-2.0.so -L/usr/x86_64-pc-linux-gnu/lib /usr/x86_64-pc-linux-gnu/lib/libgmodule-2.0.so -ldl -lz -lresolv /usr/x86_64-pc-linux-gnu/lib/libmount.so /usr/x86_64-pc-linux-gnu/lib/libblkid.so /usr/x86_64-pc-linux-gnu/lib/libuuid.so -lrt /usr/x86_64-pc-linux-gnu/lib/libgobject-2.0.so /usr/x86_64-pc-linux-gnu/lib/libffi.so /usr/x86_64-pc-linux-gnu/lib/libglib-2.0.so /usr/x86_64-pc-linux-gnu/lib/libpcre.so -lpthread  -O2 -march=native -Wl,--no-undefined   -pthread -Wl,-soname -Wl,libbd_utils.so.2 -o .libs/libbd_utils.so.2.1.0
.libs/libbd_utils_la-dev_utils.o: In function `bd_utils_get_device_symlinks':
dev_utils.c:(.text+0x11d): undefined reference to `udev_new'
dev_utils.c:(.text+0x133): undefined reference to `udev_device_new_from_subsystem_sysname'
dev_utils.c:(.text+0x147): undefined reference to `udev_device_get_devlinks_list_entry'
dev_utils.c:(.text+0x17b): undefined reference to `udev_list_entry_get_next'
dev_utils.c:(.text+0x1a8): undefined reference to `udev_list_entry_get_name'
dev_utils.c:(.text+0x1bd): undefined reference to `udev_list_entry_get_next'
dev_utils.c:(.text+0x1d5): undefined reference to `udev_device_unref'
dev_utils.c:(.text+0x1dd): undefined reference to `udev_unref'
dev_utils.c:(.text+0x21a): undefined reference to `udev_device_unref'
dev_utils.c:(.text+0x222): undefined reference to `udev_unref'
dev_utils.c:(.text+0x253): undefined reference to `udev_unref'
collect2: error: ld returned 1 exit status
make[2]: Leaving directory '/var/tmp/paludis/build/base-libblockdev-2.8/work/libblockdev-libblockdev-2.8-1/src/utils'
make[2]: *** [Makefile:470: libbd_utils.la] Error 1
make[1]: *** [Makefile:413: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/paludis/build/base-libblockdev-2.8/work/libblockdev-libblockdev-2.8-1/src'
make: *** [Makefile:473: all-recursive] Error 1
[...]
```

Please see the attached file for a full build log.

**Comment by vpodzime** [comment]
Can you please check what ``pkg-config --libs libudev`` returns? The above links just fine on all our testing systems (F25, F26, Rawhide, CentOS 7).

**Comment by tgurr** [comment]
```
# /usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-pkg-config --libs libudev
-ludev
```
If I understand the logic correctly configure.ac seems to only pkg-config check for (lib-)udev when --with-dm is given:

```
AS_IF([test "x$with_dm" != "xno"],
      [LIBBLOCKDEV_PKG_CHECK_MODULES([UDEV], [libudev >= 216])
       LIBBLOCKDEV_CHECK_HEADER([dmraid/dmraid.h], [], [dmraid.h not available])
      ],
      [])
```
Did you try to reproduce the issue with my configure options posted above? So with --without-dm?


Because with the following change it seems to work for me as well (if you think that's a proper fix I'd provide a proper pull request for the change):

```
diff -Naur libblockdev-libblockdev-2.8-1/configure.ac libblockdev-libblockdev-2.8-1.new/configure.ac
--- libblockdev-libblockdev-2.8-1/configure.ac	2017-06-06 13:52:02.000000000 +0200
+++ libblockdev-libblockdev-2.8-1.new/configure.ac	2017-06-08 12:29:52.664476021 +0200
@@ -125,6 +125,7 @@
 LIBBLOCKDEV_PKG_CHECK_MODULES([GLIB], [glib-2.0 >= 2.42.2])
 LIBBLOCKDEV_PKG_CHECK_MODULES([GOBJECT], [gobject-2.0 >= 2.42.2])
 LIBBLOCKDEV_PKG_CHECK_MODULES([GIO], [gio-2.0 >= 2.42.2])
+LIBBLOCKDEV_PKG_CHECK_MODULES([UDEV], [libudev >= 216])
 
 AS_IF([test "x$with_crypto" != "xno"],
       [LIBBLOCKDEV_PKG_CHECK_MODULES([CRYPTSETUP], [libcryptsetup >= 1.6.7])
@@ -138,9 +139,7 @@
       [])
 
 AS_IF([test "x$with_dm" != "xno"],
-      [LIBBLOCKDEV_PKG_CHECK_MODULES([UDEV], [libudev >= 216])
-       LIBBLOCKDEV_CHECK_HEADER([dmraid/dmraid.h], [], [dmraid.h not available])
-      ],
+       LIBBLOCKDEV_CHECK_HEADER([dmraid/dmraid.h], [], [dmraid.h not available]),
       [])
 
 AS_IF([test "x$with_kbd" != "xno"],
```

```
/bin/sh ../../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-cc -I/usr/x86_64-pc-linux-gnu/include/glib-2.0 -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include  -Wall -Wextra -Werror -pipe -O2 -march=native -version-info 3:0:1 -Wl,--no-undefined  -o libbd_utils.la -rpath /usr/x86_64-pc-linux-gnu/lib libbd_utils_la-exec.lo libbd_utils_la-extra_arg.lo libbd_utils_la-dev_utils.lo -lglib-2.0 -lm -lgio-2.0 -lgobject-2.0 -lglib-2.0 -ludev 
libtool: link: x86_64-pc-linux-gnu-cc -shared  -fPIC -DPIC  .libs/libbd_utils_la-exec.o .libs/libbd_utils_la-extra_arg.o .libs/libbd_utils_la-dev_utils.o   -Wl,-rpath -Wl,/usr/x86_64-pc-linux-gnu/lib -Wl,-rpath -Wl,/usr/x86_64-pc-linux-gnu/lib /usr/x86_64-pc-linux-gnu/lib/libgio-2.0.so -L/usr/x86_64-pc-linux-gnu/lib /usr/x86_64-pc-linux-gnu/lib/libgmodule-2.0.so -ldl -lz /usr/x86_64-pc-linux-gnu/lib/libmount.so /usr/x86_64-pc-linux-gnu/lib/libblkid.so /usr/x86_64-pc-linux-gnu/lib/libuuid.so /usr/x86_64-pc-linux-gnu/lib/libgobject-2.0.so /usr/x86_64-pc-linux-gnu/lib/libffi.so /usr/x86_64-pc-linux-gnu/lib/libglib-2.0.so /usr/x86_64-pc-linux-gnu/lib/libpcre.so -lpthread /usr/x86_64-pc-linux-gnu/lib/libudev.so -lresolv -lcap -lrt -lm  -O2 -march=native -Wl,--no-undefined   -pthread -Wl,-soname -Wl,libbd_utils.so.2 -o .libs/libbd_utils.so.2.1.0
```

**Comment by vpodzime** [comment]
Good point, you're right! I'll update the ``./configure.ac`` file. Thanks!

**Comment by vpodzime** [comment]
Pushed as https://github.com/rhinstaller/libblockdev/commit/50dec146ddd6c77f5989aa359a545ab676437169

**Comment by tgurr** [comment]
Could you maybe have a deeper look into it because I think it's not the only problem related to the build options. After getting past the udev linking problem I ran into some others (I'm currently still unable to build libblockdev).

The first one was something about `No package 'bytesize' found` despite passing --without-btrfs and --without-mdraid to configure which to my understanding shouldn't require libbytesize.

And after installing libbytesize I ran into

```
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: cannot find -ldmraid
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/sh', '../../libtool', '--mode=link', '--tag=CC', 'x86_64-pc-linux-gnu-cc', '-o', '/var/tmp/paludis/build/base-libblockdev-2.8amic', '-pipe', '-O2', '-march=native', '-pipe', '-O2', '-march=native', 'tmp-introspectl90u_bg7/var/tmp/paludis/build/base-libblockdev-2.8/work/libblockdev-libblockdev-2.8-1/srd_utils', '-L./../utils/', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-ldevmapper', '-ludev', '-lcryptsetup', '-lparted', '-lblkid', '-l
make[3]: *** [/usr/share/gobject-introspection-1.0/Makefile.introspection:160: BlockDev-2.0.gir] Error 1
make[2]: *** [Makefile:707: all-recursive] Error 1
make[1]: *** [Makefile:413: all-recursive] Error 1
make: *** [Makefile:473: all-recursive] Error 1
```
which shouldn't happen because of --without-mdraid.

**Comment by vpodzime** [comment]
Sure, I'll go through the options and try some combinations.

**Comment by vpodzime** [comment]
@tgurr could you please check if https://github.com/rhinstaller/libblockdev/pull/209 fixes or at least improves things for you?

**Comment by tgurr** [comment]
@vpodzime Thank you very much! With this change I'm able to successfully compile libblockdev-2.8.

One remaining problem I see is that there's a --enable-introspection configure flag, but disabling it results in an immediate failure running configure:

```
[...]
config.status: creating data/conf.d/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands

*** Libblockdev encountered the following issues during configuration:
GObject introspection (devel) must be installed and enabled

*** Libblockdev will not successfully build without these missing dependencies
```
If libblockdev isn't supposed to work without gobject-introspection maybe the flag should be removed.

**Comment by vpodzime** [comment]
> If libblockdev isn't supposed to work without gobject-introspection maybe the flag should be removed.

Yeah, that's the easiest way to go because the GI support is one of the greatest things about *libblockdev*. However, I see cases where just the C API is enough so I'll try to make things work without GI too. Let me see to that early next week. Thanks!

**Comment by vpodzime** [comment]
> If libblockdev isn't supposed to work without gobject-introspection maybe the flag should be removed.
> 
> Yeah, that's the easiest way to go because the GI support is one of the greatest things about libblockdev. However, I see cases where just the C API is enough so I'll try to make things work without GI too. Let me see to that early next week. Thanks!

Addressed with https://github.com/rhinstaller/libblockdev/pull/210. @tgurr, could you please check it out? Thanks!

**Comment by tgurr** [comment]
@vpodzime Compiling libblockdev now certainly works for me with your patch applied if gobject-introspection is not around (see additional comment below) and also for the case where it is around but one disables it.

However if I re-run autotools without gobject-introspection being present on the system I end up with a configure not having the introspection switch.

gobject-introspection installed and running ./autogen && ./configure --help with your patch applied:
```
  --disable-libtool-lock  avoid locking (might break parallel builds)
  --enable-introspection=[no/auto/yes]
                          Enable introspection for this build
  --enable-tests          Run tests at compile time (default=yes)
```
gobject-introspection **NOT** installed and running ./autogen && ./configure --help with your patch applied:
```
  --disable-libtool-lock  avoid locking (might break parallel builds)
  --enable-tests          Run tests at compile time (default=yes)
```
Not sure if this is intended. It gives a warning about a missing configure option during build when building without gobject-introspection support and the gobject-introspection package not being present on the system. However that's not an error and now I'm not quite sure how other packages handle this case and/or behave similiar.

**Comment by vpodzime** [comment]
> Not sure if this is intended. It gives a warning about a missing configure option during build when building without gobject-introspection support and the gobject-introspection package not being present on the system. However that's not an error and now I'm not quite sure how other packages handle this case and/or behave similiar.

Well, all that is provided by the GI macros and I really don't want to duplicate everything in *libblockdev*'s codebase. Is ``./configure --disable-introspection`` (or without the option) failing or just giving a warning? If it's just a warning, I'd be willing to just live with it.

**Comment by tgurr** [comment]
It builds just fine, just issuing a warning about the unknown configure option:
`configure: WARNING: unrecognized options: --disable-introspection`
I can live with that as well.

**Comment by vpodzime** [comment]
> I can live with that as well.

Great. :) Anything else? If not, I'd do a new upstream release with all the fixes we have put together in the recent few days. No new features, but still worth a new release, I think.

**Comment by tgurr** [comment]
For now we're all set I think. Every problem fixed and every change we shipped downstream has been upstreamed. There's only one minor thing about selecting the right Python version which we have to do downstream, but that's distribution specific and may also be a shortcomming of the way we have to do things. Huge thanks for your help with everything and the awesome response times. It's a pleasure to work with you!

**Comment by vpodzime** [comment]
> For now we're all set I think. Every problem fixed and every change we shipped downstream has been upstreamed. There's only one minor thing about selecting the right Python version which we have to do downstream, but that's distribution specific and may also be a shortcomming of the way we have to do things.

Great! Which downstream are you representing/working for? I take it you guys support multiple versions of Python?


> Huge thanks for your help with everything and the awesome response times. It's a pleasure to work with you!

No problem at all. Thanks for helping with hunting down all those issues and your patches!

**Comment by tgurr** [comment]
I'm working on Exherbo Linux, a rather small source-based distribution (for the regular non technical desktop users I still advice them to go with the Fedora KDE spin). On Exherbo we've a few neat features, for example regarding multiarch/cross support: https://exherbo.org/docs/multiarch-pr.html which often requires such fixes to build systems like being able to set some tools like the pkg-config and gcc command since we've them prefixed with the host triplet so on Exherbo the host environment is not any special or different from having additional cross ones. We try our best to get our fixes upstream for others to benefit from them as well and it eases the downstream maintenance work on version bumps not having to additionally port the patches every time a new version appears.

We support multiple version of Python and allow to set them individually for each package (and their dependencies). For libblockdev I had the problem that the Python2/3 support is tied to a configure flag which doesn't play well together with the way we handle things. So for now I disable Python3 by passing --without-python3 and then sed the right Python version in src/python/gi/overrides/Makefile.am.

```
    edo sed \
        -e "s:shell python:shell ${PYTHON}:g" \
        -i src/python/gi/overrides/Makefile.am
```
But I consider this to be a distribution specific hack, or better said I lack any idea how to change things so it would fit for everyone.

**Comment by vpodzime** [comment]
Wow, really nice. Thanks for the extra info! I think this issue can now be closed, right?

**Comment by tgurr** [comment]
Indeed, thanks!
