### ISSUE TITLE
Parted warning is treated as an error

### ISSUE THREAD

**Issue by squimrel** [rhinstaller/libblockdev#214]
Currently any parted exception is treated as an error (which leads to abort). A parted exception may be only a warning and it should be treated as such in that case.

I would love to work on a PR to fix this.

I'm not sure how warnings should be treated in this library and therefore suggestions are welcome.

Furthermore this issue is a question on whether PRs on this are welcome at all.

**Comment by vpodzime** [comment]
> Currently any parted exception is treated as an error (which leads to abort). A parted exception may be only a warning and it should be treated as such in that case.

Do you have any particular example?


> I'm not sure how warnings should be treated in this library and therefore suggestions are welcome.
> 
> Furthermore this issue is a question on whether PRs on this are welcome at all.

PRs are always welcome! I think the easiest solution would be to just propagate the warnings with ``g_warning()`` so that they are not completely lost. Well, as long as they can be safely ignored otherwise. I don't really want to introduce any new mechanism for warnings to the library.

**Comment by squimrel** [comment]
> Do you have any particular example?

For example [src/plugins/part.c#L819-L826](https://github.com/rhinstaller/libblockdev/blob/dbe13d5ca58d698b340a268f5ce3556e56e07616/src/plugins/part.c#L819-L826) may not be an error.

[src/plugins/part_err.c#L26-L29](https://github.com/rhinstaller/libblockdev/blob/ff2d3375e7bfd7e25b161014efda1173f74d892c/src/plugins/part_err.c#L26-L29) is responsible for catching warnings.

Note that parted marks the exceptions as whether the user may ignore them or not.

**Comment by vpodzime** [comment]
> For example src/plugins/part.c#L819-L826 may not be an error.

I think that trying to create a partition on a block device that has no partition table is an error, isn't it?


> Note that parted marks the exceptions as whether the user may ignore them or not.

I know, but it really depends on the (external/libblockdev) context in which the exception was reported.

**Comment by squimrel** [comment]
> I think that trying to create a partition on a block device that has no partition table is an error, isn't it?

Well that code simply assumes that it failed to read the partition table but that may not always be the case. The errors messages reported by libblockdev are very inaccurate.

> I know, but it really depends on the (external/libblockdev) context in which the exception was reported.

If they can be ignored they should be ignored IMHO. Warn early fail late if at all.

**Comment by vpodzime** [comment]
> Well that code simply assumes that it failed to read the partition table but that may not always be the case. The errors messages reported by libblockdev are very inaccurate.

Well, from libblockdev's perspective it is exactly as it says -- it tried to create an object (struct) representing the partition table and that failed.


> If they can be ignored they should be ignored IMHO. Warn early fail late if at all.

Sure, but how can it be ignored if the following code needs the object (struct) *libparted* didn't return?

**Comment by squimrel** [comment]
> Sure, but how can it be ignored if the following code needs the object (struct) libparted didn't return?

It would return the object if the warning would be caught in 
[src/plugins/part_err.c#L26-L29](https://github.com/rhinstaller/libblockdev/blob/ff2d3375e7bfd7e25b161014efda1173f74d892c/src/plugins/part_err.c#L26-L29). It only doesn't return if the exception is unhandled. That's how libparted works.

**Comment by vpodzime** [comment]
> It would return the object if the warning would be caught in
> src/plugins/part_err.c#L26-L29. It only doesn't return if the exception is unhandled. That's how libparted works.

Oh, I see what you mean now. Well, libblockdev could do better than. Feel free to submit a PR with improvements. ;)
