### ISSUE TITLE
Btrfs: Should be using ioctls instead of wrapping command line

### ISSUE THREAD

**Issue by agrover** [rhinstaller/libblockdev#37]
ioctls exist for btrfs (indeed this is what btrfs-progs is using.) Instead of wrapping the command-line tool, which can change, and is meant for human consumption, libblockdev should use the ioctls directly. This is the only btrfs API guaranteed to be stable.

**Comment by vpodzime** [comment]
The only possible scenario for that to happen is if *btrfs-progs* started using *libblockdev* then which I think is not going to happen. So the proper solution for this issue is to create something like *libbtrfs* used by both *btrfs-progs* and *libblockdev*.

**Comment by agrover** [comment]
btrfs-progs would have a reason to use libblockdev?

but in any case I agree, a libbtrfs would be nice and I actually worked on this but licensing issues interfered (btrfs-progs is GPL not LGPL).

**Comment by vpodzime** [comment]
This is never going to happen, sorry. If/once there is something like *libbtrfs*, I'll gladly start using it. But that would be a different GH issue.
