### ISSUE TITLE
RFE: Generic file system resizing support

### ISSUE THREAD

**Issue by tsmetana** [rhinstaller/libblockdev#61]
Hello,
  I'm missing the support for generic filesystem resizing (see fsadm(8)). Having an option to resize the underlying file system in lvresize would be nice too ("lvresize -r").

**Comment by vpodzime** [comment]
I'm not sure a low-level library like *libblockdev* should support things like this. I'm leaving this open, but it's definitely a low-prio thing.

**Comment by tsmetana** [comment]
There is a support for BTRFS resizing already: https://rhinstaller.github.io/libblockdev/libblockdev-BTRFS.html#bd-btrfs-resize
